# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tests

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Use the Node.js version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Dependencies
      - name: Install Dev Dependencies
        run: npm install

      # Linter
      - name: Run linter
        run: npm run linter
        continue-on-error: false
  
      # Build and test
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      # Use the Node.js to publish to npm
      - name: Use Node.js 20.x to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      # Publish
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
